### ISSUE TITLE
Installer won't launch 

### ISSUE THREAD

**Issue by lexterror** [IvanRF/MassiveFileRenamer#5]
I'm trying to run the installer on Kubuntu and nothing happens. I have JRE working for both user and root.

**Comment by lexterror** [comment]
I tried the following: 

./MassiveFileRenamer-1.6.0-linux-installer.run

and it won't launch...

**Comment by lexterror** [comment]
If I download the "master" branch will it work as a portable binary?

**Comment by lexterror** [comment]
I'm going to use the installation folder from another computer. Thanks!

**Comment by IvanRF** [comment]
Excellent! let me know if it works that way.
